### PR TITLE
Implement config saving/loading for a bare minimum set of options

### PR DESCRIPTION
**Pull request by safijari**

### CODE REVIEW

**Comment by marissa999** [comment]
i had no clue that settings_manager is a thing :D i was originally thinking about saving the settings in a webstorage (something ive seen a different plugin is doing) but that seems to be a better option. But this looks much better!

I didnt test it so far, ill try it later once im done with work. When it all works Ill approve and merge it

One thing we could also do would be to add `alwaysRender: true` to the UI. I didnt do that originally bc there were a few issues, with it showing the old settings over and over, but I think it might work now, and it should solve the issue where you can see the default view/settings for a frame when you open the plugin

**Comment by safijari** [comment]
Where's the always render thing supposed to be added?

I did some light testing and it seemed to work. Format options stuck through boot. Something to note with this is that if you enabled replay it'll persist through reboots (and works correctly). This is internted behavior but if you feel that shouldn't happen please let me know.

Also now that the watchdog is merged I need to implement a system for recognizing a return to gamemode so if replay had been running before we can have it be running again.

**Comment by marissa999** [comment]
"Where's the always render thing supposed to be added?"
At the entrypoint of the plugin.

"I did some light testing and it seemed to work. Format options stuck through boot."
Yeah I noticed that too, same also applies to the filepicker.

"Something to note with this is that if you enabled replay it'll persist through reboots (and works correctly). This is internted behavior but if you feel that shouldn't happen please let me know."
I think it would be great to have a checkbox at some point that somebody needs to check to have replaymode turn on at boot automatically. Recording does have a performance penalty after all.

"Also now that the watchdog is merged I need to implement a system for recognizing a return to gamemode so if replay had been running before we can have it be running again."
Oh yeah, I guess it shouldnt be too hard to add something like that? It probably is enough to add an `elif in_gm and not is_cap and autostart_replaymode` after the first if in the watchdog, and if so to start rolling recording again. 
Also I think currently the watchdog is only stopping recording, but not stopping rolling recording. Is that intended? 

Anyway you can take a look at the folder picker, give it a try and you can merge it if you think its good.

**Comment by safijari** [comment]
@marissa999 doesn't look like I have merge rights.

Folder picker is ok. I dislike the fact that it has no "create folder" button but that's a Decky issue. I'm good with merging this and working on the rolling record thing later.

**Review by marissa999 — APPROVED** [review]

**Pull request merged**
